const ChatActionTypes = {
  FETCH_CHATS: 'FETCH_CHATS',
  DELETE_CHAT_START: 'DELETE_CHAT_START',
  DELETE_CHAT_SUCCESS: 'DELETE_CHAT_SUCCESS',
  DELETE_CHAT_FAILURE: 'DELETE_CHAT_FAILURE',
  ONLINE: 'ONLINE',
  OFFLINE: 'OFFLINE',
  ADD_CHAT_SUCCESS: 'ADD_CHAT_SUCCESS',
  ADD_CHAT_FAILURE: 'ADD_CHAT_FAILURE',
};

export default ChatActionTypes;
