const ChatActionTypes = {
  FETCH_CHATS_START: 'FETCH_CHATS_START',
  FETCH_CHATS_SUCCESS: 'FETCH_CHATS_START',
  FETCH_CHATS_FAILURE: 'FETCH_CHATS_START',
  DELETE_CHAT_START: 'DELETE_CHAT',
  DELETE_CHAT_SUCCESS: 'DELETE_CHAT',
  DELETE_CHAT_FAILURE: 'DELETE_CHAT',
  ONLINE: 'ONLINE',
  OFFLINE: 'OFFLINE',
  ADD_CHAT_SUCCESS: 'ADD_CHAT_SUCCESS',
  ADD_CHAT_FAILURE: 'ADD_CHAT_FAILURE',
};

export default ChatActionTypes;
