const ChatActionTypes = {
  FETCH_CHATS: "FETCH_CHATS",
  DELETE_CHAT_START: "DELETE_CHAT_START",
  DELETE_CHAT_SUCCESS: "DELETE_CHAT_SUCCESS",
  DELETE_CHAT_FAILURE: "DELETE_CHAT_FAILURE",
  ONLINE: "ONLINE",
  OFFLINE: "OFFLINE",
  ADD_CHAT_SUCCESS: "ADD_CHAT_SUCCESS",
  ADD_CHAT_FAILURE: "ADD_CHAT_FAILURE",

  FETCH_MESSAGES: "FETCH_MESSAGES",
  ADD_MESSAGE: "ADD_MESSAGE",
  DELETE_MESSAGE_START: "DELETE_MESSAGE_START",
  DELETE_MESSAGE_SUCCESS: "DELETE_MESSAGE_SUCCESS",
  DELETE_MESSAGE_FAILURE: "DELETE_MESSAGE_FAILURE",
  EDIT_MESSAGE_START: "EDIT_MESSAGE_START",
  EDIT_MESSAGE_SUCCESS: "EDIT_MESSAGE_SUCCESS",
  EDIT_MESSAGE_FAILURE: "EDIT_MESSAGE_FAILURE",
  DELETE_MESSAGE_FROM_SOCKET: "DELETE_MESSAGE_FROM_SOCKET",
  MARK_MESSAGE_AS_READ: "MARK_MESSAGE_AS_READ",
};

export default ChatActionTypes;
