const ContactsActionTypes = {
  FETCH_CONTACTS_START: "FETCH_CONTACTS_START",
  FETCH_CONTACTS_SUCCESS: "FETCH_CONTACTS_SUCCESS",
  FETCH_CONTACTS_FAILURE: "FETCH_CONTACTS_FAILURE",
  ADD_CONTACT_START: "ADD_CONTACT_START",
  ADD_CONTACT_SUCCESS: "ADD_CONTACT_SUCCESS",
  ADD_CONTACT_FAILURE: "ADD_CONTACT_FAILURE",
  DELETE_CONTACT_START: "DELETE_CONTACT_START",
  DELETE_CONTACT_SUCCESS: "DELETE_CONTACT_SUCCESS",
  DELETE_CONTACT_FAILURE: "DELETE_CONTACT_FAILURE",
};