const MessageActionTypes = {
  FETCH_MESSAGES: 'FETCH_MESSAGES',
  ADD_MESSAGE: 'ADD_MESSAGE',
  DELETE_MESSAGE_START: 'DELETE_MESSAGE_START',
  DELETE_MESSAGE_SUCCESS: 'DELETE_MESSAGE_SUCCESS',
  DELETE_MESSAGE_FAILURE: 'DELETE_MESSAGE_FAILURE',
  EDIT_MESSAGE: 'EDIT_MESSAGE',
  DELETE_MESSAGE_FROM_SOCKET: 'DELETE_MESSAGE_FROM_SOCKET',
  MARK_MESSAGE_AS_READ: 'MARK_MESSAGE_AS_READ',
};

export default MessageActionTypes;
