const MessageActionTypes = {
  FETCH_MESSAGE_START: 'FETCH_MESSAGE_START',
  FETCH_MESSAGE_SUCCESS: 'FETCH_MESSAGE_SUCCESS',
  FETCH_MESSAGE_FAILURE: 'FETCH_MESSAGE_FAILURE',
  ADD_MESSAGE: 'ADD_MESSAGE',
  DELETE_MESSAGE_START: 'DELETE_MESSAGE_START',
  DELETE_MESSAGE_SUCCESS: 'DELETE_MESSAGE_SUCCESS',
  DELETE_MESSAGE_FAILURE: 'DELETE_MESSAGE_FAILURE',
};

export default MessageActionTypes;
